/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/Profile'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAssetsRouteImport } from './routes/_authenticated/assets'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated/departments'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedGovernanceRouteImport } from './routes/_authenticated/governance'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSeniorPastorCockpitRouteImport } from './routes/_authenticated/senior-pastor-cockpit'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedDepartmentsSlugRouteImport } from './routes/_authenticated/departments.$slug'
import { Route as AuthenticatedMembersIdRouteImport } from './routes/_authenticated/members.$id'
import { Route as ApiPublicHooksSendAnnouncementEmailsRouteImport } from './routes/api/public/hooks/send-announcement-emails'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/Profile',
  path: '/Profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssetsRoute = AuthenticatedAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernanceRoute = AuthenticatedGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeniorPastorCockpitRoute =
  AuthenticatedSeniorPastorCockpitRouteImport.update({
    id: '/senior-pastor-cockpit',
    path: '/senior-pastor-cockpit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepartmentsSlugRoute =
  AuthenticatedDepartmentsSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => AuthenticatedDepartmentsRoute,
  } as any)
const AuthenticatedMembersIdRoute = AuthenticatedMembersIdRouteImport.update({
  id: '/members/$id',
  path: '/members/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksSendAnnouncementEmailsRoute =
  ApiPublicHooksSendAnnouncementEmailsRouteImport.update({
    id: '/api/public/hooks/send-announcement-emails',
    path: '/api/public/hooks/send-announcement-emails',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/Profile': typeof AuthenticatedProfileRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/home': typeof AuthenticatedHomeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/senior-pastor-cockpit': typeof AuthenticatedSeniorPastorCockpitRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/departments/$slug': typeof AuthenticatedDepartmentsSlugRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/api/public/hooks/send-announcement-emails': typeof ApiPublicHooksSendAnnouncementEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/Profile': typeof AuthenticatedProfileRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/assets': typeof AuthenticatedAssetsRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/governance': typeof AuthenticatedGovernanceRoute
  '/home': typeof AuthenticatedHomeRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/senior-pastor-cockpit': typeof AuthenticatedSeniorPastorCockpitRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/departments/$slug': typeof AuthenticatedDepartmentsSlugRoute
  '/members/$id': typeof AuthenticatedMembersIdRoute
  '/api/public/hooks/send-announcement-emails': typeof ApiPublicHooksSendAnnouncementEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/Profile': typeof AuthenticatedProfileRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/assets': typeof AuthenticatedAssetsRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRouteWithChildren
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/governance': typeof AuthenticatedGovernanceRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/senior-pastor-cockpit': typeof AuthenticatedSeniorPastorCockpitRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/departments/$slug': typeof AuthenticatedDepartmentsSlugRoute
  '/_authenticated/members/$id': typeof AuthenticatedMembersIdRoute
  '/api/public/hooks/send-announcement-emails': typeof ApiPublicHooksSendAnnouncementEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/Profile'
    | '/admin'
    | '/assets'
    | '/attendance'
    | '/departments'
    | '/events'
    | '/feed'
    | '/governance'
    | '/home'
    | '/reports'
    | '/senior-pastor-cockpit'
    | '/tasks'
    | '/departments/$slug'
    | '/members/$id'
    | '/api/public/hooks/send-announcement-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/Profile'
    | '/admin'
    | '/assets'
    | '/attendance'
    | '/departments'
    | '/events'
    | '/feed'
    | '/governance'
    | '/home'
    | '/reports'
    | '/senior-pastor-cockpit'
    | '/tasks'
    | '/departments/$slug'
    | '/members/$id'
    | '/api/public/hooks/send-announcement-emails'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/Profile'
    | '/_authenticated/admin'
    | '/_authenticated/assets'
    | '/_authenticated/attendance'
    | '/_authenticated/departments'
    | '/_authenticated/events'
    | '/_authenticated/feed'
    | '/_authenticated/governance'
    | '/_authenticated/home'
    | '/_authenticated/reports'
    | '/_authenticated/senior-pastor-cockpit'
    | '/_authenticated/tasks'
    | '/_authenticated/departments/$slug'
    | '/_authenticated/members/$id'
    | '/api/public/hooks/send-announcement-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksSendAnnouncementEmailsRoute: typeof ApiPublicHooksSendAnnouncementEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/Profile': {
      id: '/_authenticated/Profile'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assets': {
      id: '/_authenticated/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthenticatedAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/governance': {
      id: '/_authenticated/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof AuthenticatedGovernanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/senior-pastor-cockpit': {
      id: '/_authenticated/senior-pastor-cockpit'
      path: '/senior-pastor-cockpit'
      fullPath: '/senior-pastor-cockpit'
      preLoaderRoute: typeof AuthenticatedSeniorPastorCockpitRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/departments/$slug': {
      id: '/_authenticated/departments/$slug'
      path: '/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof AuthenticatedDepartmentsSlugRouteImport
      parentRoute: typeof AuthenticatedDepartmentsRoute
    }
    '/_authenticated/members/$id': {
      id: '/_authenticated/members/$id'
      path: '/members/$id'
      fullPath: '/members/$id'
      preLoaderRoute: typeof AuthenticatedMembersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/send-announcement-emails': {
      id: '/api/public/hooks/send-announcement-emails'
      path: '/api/public/hooks/send-announcement-emails'
      fullPath: '/api/public/hooks/send-announcement-emails'
      preLoaderRoute: typeof ApiPublicHooksSendAnnouncementEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDepartmentsRouteChildren {
  AuthenticatedDepartmentsSlugRoute: typeof AuthenticatedDepartmentsSlugRoute
}

const AuthenticatedDepartmentsRouteChildren: AuthenticatedDepartmentsRouteChildren =
  {
    AuthenticatedDepartmentsSlugRoute: AuthenticatedDepartmentsSlugRoute,
  }

const AuthenticatedDepartmentsRouteWithChildren =
  AuthenticatedDepartmentsRoute._addFileChildren(
    AuthenticatedDepartmentsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAssetsRoute: typeof AuthenticatedAssetsRoute
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRouteWithChildren
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedGovernanceRoute: typeof AuthenticatedGovernanceRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSeniorPastorCockpitRoute: typeof AuthenticatedSeniorPastorCockpitRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedMembersIdRoute: typeof AuthenticatedMembersIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAssetsRoute: AuthenticatedAssetsRoute,
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRouteWithChildren,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedGovernanceRoute: AuthenticatedGovernanceRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSeniorPastorCockpitRoute: AuthenticatedSeniorPastorCockpitRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedMembersIdRoute: AuthenticatedMembersIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksSendAnnouncementEmailsRoute:
    ApiPublicHooksSendAnnouncementEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
